spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  data:
    mongodb:
      database: inspection
      host: 127.0.0.1
      port: 27017
      path: C:/Program Files/MongoDB/Server/4.0/bin/mongoexport.exe
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
      location: D:/temp
server:
  port: 8080
  servlet:
    context-path: /inspection